### ISSUE TITLE
Resetting password not working

### ISSUE THREAD

**Issue by PhiCoderX** [seanmorley15/AdventureLog#213]
First of all amazing project! Exactly what I was looking for.

I set up my installation and logged into the web interface with admin / admin. I changed the username, email address and password on the user account settings page to something personal. Afterwards I successfully created three adventures.

Later I tried to log in again which failed (used password manager so typos are no issue). After a restart of the stack however, the login with admin / admin still works, but none of the adventures is visible.

Resetting the password with the newly defined email creates the message in the server container log attached below. I use that link, enter my new password, and then immediately try to log in with that new password which fails. (I don't know if `Starting development server at http://0.0.0.0:8000/` is relevant.)

I attached to the database and my email address is listed in table `account_emailaddress` and the adventures are present in table `adventures_adventure`. When trying to rename the admin / admin account to the same personal username, it says that it is already in use.

Maybe something in my configuration is wrong, so I have also attached my docker compose file.

In conclusion, changing the details of the default admin account lead to the creation of a new one and the inability to access the renamed account.

### server container log
```
PostgreSQL is up - continuing...
Operations to perform:
  Apply all migrations: account, admin, adventures, auth, authtoken, contenttypes, sessions, sites, socialaccount, users, worldtravel
Running migrations:
  No migrations to apply.
Countries or regions already exist in the database. Use --force to override.
Creating superuser...
Superuser already exists.
Performing system checks...
System check identified no issues (0 silenced).
August 16, 2024 - 10:31:18
Django version 5.0.8, using settings 'main.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[16/Aug/2024 10:32:09] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 10:32:09] "POST /auth/login/ HTTP/1.1" 400 68
[16/Aug/2024 10:32:13] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 10:32:13] "POST /auth/login/ HTTP/1.1" 400 68
[16/Aug/2024 10:32:26] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 10:32:27] "POST /auth/login/ HTTP/1.1" 400 68
[16/Aug/2024 10:32:27] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 10:32:28] "POST /auth/login/ HTTP/1.1" 400 68
[16/Aug/2024 10:32:37] "POST /auth/password/reset/ HTTP/1.1" 200 49
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [example.com] Password Reset Email
From: webmaster@localhost
To: mymail@gmail.com
Date: Fri, 16 Aug 2024 14:33:27 -0000
Message-ID: <172381880778.11.11617989157896689004@ede65eb69c0d>
Hello from example.com!
You're receiving this email because you or someone else has requested a password reset for your user account.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.
http://192.168.178.10:8002/settings/forgot-password/confirm?token=cbulbr-504552f6d1bdfff099877c4f47f5b77b&uid=1
In case you forgot, your username is myusernname.
Thank you for using example.com!
example.com
-------------------------------------------------------------------------------
[16/Aug/2024 10:33:27] "POST /auth/password/reset/ HTTP/1.1" 200 49
[16/Aug/2024 10:33:49] "POST /auth/password/reset/confirm/ HTTP/1.1" 200 59
[16/Aug/2024 10:33:57] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 10:33:57] "POST /auth/login/ HTTP/1.1" 400 68
```
### Docker compose file
```
version: "3.9"

services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    environment:
      - PUBLIC_SERVER_URL=http://192.168.178.10:8001
      - ORIGIN=http://192.168.178.10:8002
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "8002:3000"
    depends_on:
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=postgrespw
      - SECRET_KEY=postgrespw
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://192.168.178.10:88'
      - CSRF_TRUSTED_ORIGINS=http://192.168.178.10:8001,http://192.168.178.10:8002
      - DEBUG=False
      - FRONTEND_URL='http://192.168.178.10:8002'
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./adventurelog_media:/code/media/

  nginx:
    image: nginx:latest
    ports:
      - "88:80" # Using port 81 to avoid conflict with your existing setup
    volumes:
      - ./adventurelog_media:/app/media
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
```
### Nginx conf
```
server {
    listen 80;
    server_name 192.168.178.10:8001;

    location /media/ {
        alias /app/media/;
    }
}
```

**Comment by seanmorley15** [comment]
I was just able to reproduce your issue. I have just released a fix. You might have to delete and try again though :(. Just make sure you `docker compose pull` to get latest image. Sorry this happened but it should be fixed now! Keep me updated!

**Comment by PhiCoderX** [comment]
Thank you for the quick response! Now I run into the problem mentioned in #204. 

I tried an incognito browser window (for cookies and cache) and setting `PUBLIC_SERVER_URL=http://server:8001` which caused `500: Internal Error` in the web UI after pressing login. 
### frontend log
```
Error in authHook: TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchCSRFToken (file:///app/build/server/chunks/index.server-CX6CQs1I.js:4:26)
    at async tryRefreshToken (file:///app/build/server/chunks/index.server-CX6CQs1I.js:13:21)
    at async authHook (file:///app/build/server/chunks/hooks.server-CKk8-UlX.js:45:21)
    at async respond (file:///app/build/server/index.js:3475:22)
    at async Array.ssr (file:///app/build/handler.js:1261:3) {
  cause: Error: connect ECONNREFUSED 192.168.240.3:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.240.3',
    port: 8001
  }
}
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 192.168.240.3:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.240.3',
    port: 8001
  }
}
```

**Comment by seanmorley15** [comment]
Ok, for this type of error can you do the following:

1. Set DEBUG = True in the backend
2. Visit the backend address /auth/login
3. login with your credentials and send a picture of what's happening

**Comment by PhiCoderX** [comment]
This comes up after the login with the default credentials.

![screenshot](https://github.com/user-attachments/assets/67cb8f3a-1b2e-4c2e-8162-6eae14c82b06)

**Comment by seanmorley15** [comment]
I think I found it :)
Try setting:
 PUBLIC_SERVER_URL=http://server:8000 instead of 8001

**Comment by PhiCoderX** [comment]
This fixed the initial admin / admin login. Unfortunately, the problem changing the username, password, and email still persists. 
My way of producing the error:

1. delete media and postgres folder for clean install
2. start up containers
3. open incognito browser window
4. log in with admin / admin
5. change username, then password, then email
6. create trip, then log out
7. open new browser window
8. login with newly set credentials fails
9. obtain logs below

### web log downloaded from Portainer
```
The origin to be set is: http://192.168.178.10:8002
Listening on 0.0.0.0:3000
[]
(node:8) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[]
changePassword
[]
[]
[]
[]
type, visited

name, London
location, London, Greater London, England, United Kingdom
date, 2024-01-01
description, 
latitude, 51.489334
longitude, -0.144055
is_public, false

collection, 
activity_types, ceremonial
rating, 
link, 
image, [object File]
[]
{ user: null }
[]
```
### server log
```
...
Successfully imported world travel data
Creating superuser...
Superuser created successfully.
Performing system checks...
System check identified no issues (0 silenced).
August 16, 2024 - 13:41:30
Django version 5.0.8, using settings 'main.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[16/Aug/2024 13:41:42] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 13:41:43] "POST /auth/login/ HTTP/1.1" 200 661
[16/Aug/2024 13:41:43] "GET /auth/user/ HTTP/1.1" 200 170
[16/Aug/2024 13:41:49] "GET /auth/user/ HTTP/1.1" 200 170
[16/Aug/2024 13:41:49] "GET /auth/user/ HTTP/1.1" 200 170
[16/Aug/2024 13:42:04] "GET /auth/user/ HTTP/1.1" 200 170
[16/Aug/2024 13:42:04] "GET /auth/user/ HTTP/1.1" 200 170
[16/Aug/2024 13:42:04] "PATCH /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:04] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:04] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:04] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:04] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:15] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:15] "POST /auth/password/change/ HTTP/1.1" 200 41
[16/Aug/2024 13:42:15] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:15] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:15] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:25] "GET /auth/user/ HTTP/1.1" 200 190
[16/Aug/2024 13:42:25] "POST /auth/change-email/ HTTP/1.1" 200 40
[16/Aug/2024 13:42:25] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:26] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:26] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:30] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:30] "GET /api/adventures/filtered?types=visited,planned&order_by=updated_at&order_direction=asc&include_collections=false&page=1 HTTP/1.1" 301 0
Ordering by: -updated_at
[16/Aug/2024 13:42:30] "GET /api/adventures/filtered/?types=visited,planned&order_by=updated_at&order_direction=asc&include_collections=false&page=1 HTTP/1.1" 200 52
[16/Aug/2024 13:42:34] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:34] "GET /api/activity-types/types/ HTTP/1.1" 200 2
[16/Aug/2024 13:42:49] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:49] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 13:42:49] "POST /api/adventures/ HTTP/1.1" 201 436
[16/Aug/2024 13:42:58] "GET /auth/user/ HTTP/1.1" 200 189
[16/Aug/2024 13:42:58] "POST /auth/logout/ HTTP/1.1" 200 37
[16/Aug/2024 13:43:24] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 13:43:25] "POST /auth/login/ HTTP/1.1" 400 68
```

At this point neither the login with the new credentials nor with admin / admin is possible.

1. restart all containers
2. login with new credentials still fails
3. login with admin / admin is possible again

### Restarted server log
```
PostgreSQL is up - continuing...
Operations to perform:
  Apply all migrations: account, admin, adventures, auth, authtoken, contenttypes, sessions, sites, socialaccount, users, worldtravel
Running migrations:
  No migrations to apply.
Countries or regions already exist in the database. Use --force to override.
Creating superuser...
Superuser created successfully.
Performing system checks...
System check identified no issues (0 silenced).
August 16, 2024 - 13:47:53
Django version 5.0.8, using settings 'main.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[16/Aug/2024 13:48:19] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 13:48:19] "POST /auth/login/ HTTP/1.1" 400 68
[16/Aug/2024 13:48:24] "GET /csrf/ HTTP/1.1" 200 81
[16/Aug/2024 13:48:24] "POST /auth/login/ HTTP/1.1" 200 661
[16/Aug/2024 13:48:25] "GET /auth/user/ HTTP/1.1" 200 170
```

I hope this somehow helps.

**Comment by seanmorley15** [comment]
I just created a fresh install of AdventureLog and followed the steps above, and had success with the new credentials. I have fixed an issue in the latest release so make sure you do `docker compose pull` then `docker compose up -d` for a new install.
I hope this works!

**Comment by PhiCoderX** [comment]
Unfortunately, the problem is still present for me. I have located it to be the username change of the admin account. If I only change email or password I can log in with the new password and `admin` as username (works as intended).

The login fails as soon as I change the username from admin to something else. Is it maybe mandatory that a user with the name admin exists? After restarting the containers I can log in again with admin / admin. There seems to be a check for a user named admin as a new superuser is being created on second startup where it should not be present anymore.
```
Creating superuser...
Superuser created successfully.
```

**Comment by seanmorley15** [comment]
Yes you are totally right, I have been able to fix the startup script and should be all fixed now if you `docker compose pull` the latest image.
Fixed in #228 
Thanks so much for taking the time to figure this out!

**Comment by seanmorley15** [comment]
I will close this issue because it was fixed, feel free to reopen or make a new one if there is anything else to add.
Thanks!
